// AUTO-GENERATED by scripts/Export-OpenScadStl.ps1 - do not edit by hand
// Source: print-stamp-config.json

info_stamp_line1 = "Verminology";
info_stamp_line2 = "Liquid Bait Station";
info_stamp_line3 = "v2.4.1 Prototype";
reservoir_stamp_bottom = false;
station_stamp_bottom = true;
needle_insert_export_stamp_bottom = false;
needle_gasket_export_stamp_bottom = false;
needle_seal_stamp_bottom = false;
