#!/usr/bin/env bash
# Linux/macOS CI/local: same behavior as Export-OpenScadStl.ps1
# Usage:
#   ./export-open-scad-stl.sh               # normal: export all parts
#   ./export-open-scad-stl.sh --qr-tag      # generate 1 unique QR tag STL
#   ./export-open-scad-stl.sh --qr-tag 10   # generate 10 unique QR tag STLs
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$MODEL_DIR/build-config.json"

QR_MODE=false
QR_COUNT=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --qr-tag)
      QR_MODE=true
      if [[ "${2:-}" =~ ^[0-9]+$ ]]; then
        QR_COUNT="$2"; shift
      fi
      shift ;;
    *) shift ;;
  esac
done

escape_scad() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

stem_from_scad() {
  local base
  base="$(basename "$1" .scad)"
  echo "${base//-/_}"
}

cd "$MODEL_DIR"
PROTOTYPE="$(jq -r '.prototype' "$CONFIG")"

BRAND="$(jq -r '.brand_name' "$CONFIG")"
PROD="$(jq -r '.product_name' "$CONFIG")"
VER="$(jq -r '.product_version' "$CONFIG" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

if [[ "${LBS_PRODUCTION:-}" == "1" ]]; then
  VERSION_FOLDER="$VER"
  LINE3="$VER"
  SCAD_PROTOTYPE="false"
else
  VERSION_FOLDER="${VER}-prototype"
  LINE3="$VER"
  SCAD_PROTOTYPE="$PROTOTYPE"
  if [[ "$PROTOTYPE" == "true" ]]; then
    LINE3="$VER Prototype"
  fi
fi
LINE3="$(echo "$LINE3" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

# Collect per-export stamp flags once (reused in normal + QR modes)
STAMP_FLAGS=""
while IFS= read -r row; do
  scad="$(echo "$row" | jq -r '.scad')"
  face="$(echo "$row" | jq -r '.stamp.face // empty')"
  st="$(stem_from_scad "$scad")"
  if [[ "$face" == "bottom" ]]; then
    STAMP_FLAGS+="${st}_stamp_bottom = true;"$'\n'
  else
    STAMP_FLAGS+="${st}_stamp_bottom = false;"$'\n'
  fi
done < <(jq -c '.exports[]' "$CONFIG")

write_stamp() {
  local url="${1:-}"
  local half="${2:-background}"
  local stamp_file="$MODEL_DIR/build-stamp.scad"
  {
    echo "// AUTO-GENERATED by scripts/export-open-scad-stl.sh - do not edit by hand"
    echo ""
    printf 'info_stamp_line1 = "%s";\n' "$(escape_scad "$BRAND")"
    printf 'info_stamp_line2 = "%s";\n' "$(escape_scad "$PROD")"
    printf 'info_stamp_line3 = "%s";\n' "$(escape_scad "$LINE3")"
    printf 'qr_url = "%s";\n' "$(escape_scad "$url")"
    printf 'qr_half = "%s";\n' "$half"
    printf '%s' "$STAMP_FLAGS"
  } > "$stamp_file"
}

STAMP_FILE="$MODEL_DIR/build-stamp.scad"
write_stamp ""
echo "Wrote $STAMP_FILE"

if ! command -v openscad >/dev/null 2>&1; then
  echo "openscad not in PATH; install OpenSCAD to export STLs." >&2
  exit 1
fi

EXPORT_DEFS=(-D "prototype=$SCAD_PROTOTYPE" -D "crosssection_view=false")

if $QR_MODE; then
  # ── QR Tag mode: generate light + dark pairs ──
  BASE_URL="$(jq -r '.qr_tag.base_url' "$CONFIG")"
  QR_SCAD="$(jq -r '.qr_tag.scad' "$CONFIG")"

  # Determine next sequence number from existing files
  OUT_FOLDER="$MODEL_DIR/latest-builds/$VERSION_FOLDER"
  NEXT_SEQ=0
  if [[ -d "$OUT_FOLDER" ]]; then
    while IFS= read -r fname; do
      if [[ "$fname" =~ ^reservoir-([0-9]{3})- ]]; then
        n=$((10#${BASH_REMATCH[1]}))
        if (( n >= NEXT_SEQ )); then NEXT_SEQ=$((n + 1)); fi
      fi
    done < <(ls "$OUT_FOLDER" 2>/dev/null | grep -E '^reservoir-[0-9]{3}-.*-background\.stl$')
  fi

  for (( i=1; i<=QR_COUNT; i++ )); do
    seq="$(printf '%03d' "$NEXT_SEQ")"
    NEXT_SEQ=$((NEXT_SEQ + 1))
    uuid="$(uuidgen | tr '[:upper:]' '[:lower:]')"
    url="${BASE_URL}${uuid}"

    for half in background contrast; do
      write_stamp "$url" "$half"
      stl_tmpl="$(jq -r ".qr_tag.${half}.stl" "$CONFIG")"
      stl="${stl_tmpl//\{version_folder\}/$VERSION_FOLDER}"
      stl="${stl//\{seq\}/$seq}"
      stl="${stl//\{uuid\}/$uuid}"
      out_path="$MODEL_DIR/$stl"
      mkdir -p "$(dirname "$out_path")"
      echo "QR tag $i/$QR_COUNT [$half]  $uuid -> $stl"
      openscad "${EXPORT_DEFS[@]}" -o "$out_path" "$MODEL_DIR/$QR_SCAD"
    done
  done

  write_stamp ""
  echo "Generated $QR_COUNT QR tag pair(s) (light + dark). build-stamp.scad restored to default."
else
  # ── Normal mode ──
  while IFS= read -r row; do
    scad="$(echo "$row" | jq -r '.scad')"
    stl_raw="$(echo "$row" | jq -r '.stl')"
    stl="${stl_raw//\{version_folder\}/$VERSION_FOLDER}"
    stl="${stl//\{product_version\}/$VERSION_FOLDER}"
    out_path="$MODEL_DIR/$stl"
    mkdir -p "$(dirname "$out_path")"
    echo "Export $scad -> $stl"
    openscad "${EXPORT_DEFS[@]}" -o "$out_path" "$MODEL_DIR/$scad"
  done < <(jq -c '.exports[]' "$CONFIG")
  echo "Done."
fi
