<#
.SYNOPSIS
  Regenerates stamp_generated.scad from build-config.json and exports STLs via OpenSCAD.
#>
param(
    [string]$ConfigPath = (Join-Path $PSScriptRoot "..\build-config.json")
)

$ErrorActionPreference = "Stop"
$ConfigPath = (Resolve-Path -LiteralPath $ConfigPath).Path
$ModelDir = Split-Path -Parent $ConfigPath

$cfg = Get-Content -LiteralPath $ConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Escape-ScadString([string]$s) {
    if ($null -eq $s) { return "" }
    $s = $s.Replace('\', '\\')
    return $s.Replace('"', '\"')
}

function Get-ScadStem([string]$relativeScadPath) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($relativeScadPath)
    return ($name -replace '-', '_')
}

# Stamp lines: 1 brand, 2 product, 3 version (+ Prototype if config says so, unless LBS_PRODUCTION=1)
$line1 = [string]$cfg.brand_name
$line2 = [string]$cfg.product_name
$verTag = [string]$cfg.product_version.Trim()
$isProduction = ($env:LBS_PRODUCTION -eq "1")
if ($isProduction) {
    $line3 = $verTag
    $scadPrototype = "false"
} elseif ($cfg.prototype -eq $true) {
    $line3 = ("{0} Prototype" -f $verTag).Trim()
    $scadPrototype = "true"
} else {
    $line3 = $verTag
    $scadPrototype = "false"
}

$stampPath = Join-Path $ModelDir "stamp_generated.scad"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by scripts/Export-OpenScadStl.ps1 - do not edit by hand")
[void]$sb.AppendLine("// Source: build-config.json")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(('info_stamp_line1 = "{0}";' -f (Escape-ScadString $line1)))
[void]$sb.AppendLine(('info_stamp_line2 = "{0}";' -f (Escape-ScadString $line2)))
[void]$sb.AppendLine(('info_stamp_line3 = "{0}";' -f (Escape-ScadString $line3)))

$exports = @($cfg.exports)
foreach ($exp in $exports) {
    $stem = Get-ScadStem $exp.scad
    $on = $false
    if ($null -ne $exp.stamp -and $exp.stamp.face -eq "bottom") { $on = $true }
    [void]$sb.AppendLine(('{0}_stamp_bottom = {1};' -f $stem, ($(if ($on) { "true" } else { "false" }))))
}

[System.IO.File]::WriteAllText($stampPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $stampPath"

function Find-OpenScad {
    $pf86 = [Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
    foreach ($c in @(
            $env:OPENSCAD_PATH,
            "${env:ProgramFiles}\OpenSCAD\openscad.com",
            "${env:ProgramFiles}\OpenSCAD\openscad.exe",
            $(if ($pf86) { Join-Path $pf86 "OpenSCAD\openscad.com" })
        )) {
        if ($c -and (Test-Path -LiteralPath $c)) { return $c }
    }
    $cmd = Get-Command openscad -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Path }
    return $null
}

$openscad = Find-OpenScad
if (-not $openscad) {
    throw "OpenSCAD not found. Set OPENSCAD_PATH or install OpenSCAD."
}

# STL export: full mesh quality, no cross-section.
# Each export "stl" may contain {version_folder}: <product_version> or <product_version>-prototype
# unless env LBS_PRODUCTION=1 (production → version only, no Prototype stamp).
$exportDefines = @("-D", "prototype=$scadPrototype", "-D", "crosssection_view=false")
$versionFolder = if ($isProduction) { $verTag } else { "{0}-prototype" -f $verTag }

foreach ($exp in $exports) {
    $in = Join-Path $ModelDir $exp.scad
    $relStl = [string]$exp.stl -replace '\{version_folder\}', $versionFolder
    $relStl = $relStl -replace '\{product_version\}', $versionFolder
    $relStl = $relStl -replace '/', [IO.Path]::DirectorySeparatorChar
    $out = [IO.Path]::GetFullPath([IO.Path]::Combine($ModelDir, $relStl))
    $outDir = Split-Path -Parent $out
    if (-not (Test-Path -LiteralPath $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }
    Write-Host "Export $($exp.scad) -> $relStl"
    & $openscad @exportDefines -o $out $in
    if ($LASTEXITCODE -ne 0) {
        throw "OpenSCAD failed for $($exp.scad) (exit $LASTEXITCODE)"
    }
}

Write-Host "Done."
