#!/usr/bin/env bash
# Linux/macOS CI/local: same behavior as Export-OpenScadStl.ps1
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$MODEL_DIR/print-stamp-config.json"

escape_scad() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

stem_from_scad() {
  local base
  base="$(basename "$1" .scad)"
  echo "${base//-/_}"
}

cd "$MODEL_DIR"
PREVIEW="$(jq -r '.preview' "$CONFIG")"

BRAND="$(jq -r '.brand_name' "$CONFIG")"
PROD="$(jq -r '.product_name' "$CONFIG")"
VER="$(jq -r '.product_version' "$CONFIG" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
LINE3="$VER"
if [[ "$PREVIEW" == "true" ]]; then
  LINE3="$VER Prototype"
  LINE3="$(echo "$LINE3" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
fi

STAMP_FILE="$MODEL_DIR/stamp_generated.scad"
{
  echo "// AUTO-GENERATED by scripts/export-open-scad-stl.sh - do not edit by hand"
  echo ""
  printf 'info_stamp_line1 = "%s";\n' "$(escape_scad "$BRAND")"
  printf 'info_stamp_line2 = "%s";\n' "$(escape_scad "$PROD")"
  printf 'info_stamp_line3 = "%s";\n' "$(escape_scad "$LINE3")"
  while IFS= read -r row; do
    scad="$(echo "$row" | jq -r '.scad')"
    face="$(echo "$row" | jq -r '.stamp.face // empty')"
    st="$(stem_from_scad "$scad")"
    if [[ "$face" == "bottom" ]]; then
      echo "${st}_stamp_bottom = true;"
    else
      echo "${st}_stamp_bottom = false;"
    fi
  done < <(jq -c '.exports[]' "$CONFIG")
} > "$STAMP_FILE"
echo "Wrote $STAMP_FILE"

if ! command -v openscad >/dev/null 2>&1; then
  echo "openscad not in PATH; install OpenSCAD to export STLs." >&2
  exit 1
fi

EXPORT_DEFS=(-D "mesh_preview=false" -D "crosssection_view=false")
VER="$(jq -r '.product_version' "$CONFIG" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

while IFS= read -r row; do
  scad="$(echo "$row" | jq -r '.scad')"
  stl_raw="$(echo "$row" | jq -r '.stl')"
  stl="${stl_raw//\{product_version\}/$VER}"
  out_path="$MODEL_DIR/$stl"
  mkdir -p "$(dirname "$out_path")"
  echo "Export $scad -> $stl"
  openscad "${EXPORT_DEFS[@]}" -o "$out_path" "$MODEL_DIR/$scad"
done < <(jq -c '.exports[]' "$CONFIG")

echo "Done."
